binary_build_commands: make install
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
images:
- dockerfile_path: build/ci-tf-e2e.Dockerfile
  to: ocm-tf-provider
promotion:
  namespace: ci
  tag: latest
  tag_by_commit: true
releases:
  latest:
    integration:
      name: "4.13"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: terraform-redhat
  repo: terraform-provider-ocm
  variant: images
